import type { AppProps } from 'next/app'
import Head from 'next/head'
import Script from 'next/script'
import '../styles/globals.css'

import '@zendeskgarden/css-bedrock'
import { ThemeProvider } from '@zendeskgarden/react-theming'

// Envoy components
import AppNav from '../components/AppNav'

function NCPApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider>
      <Head>
        <title>NCP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='app mx-auto max-w-4xl overflow-visible'>
        <div className='sticky top-0 z-50 flex flex-col gap-3'>
          <Script
            type='text/javascript'
            src='https://static.zdassets.com/zendesk_app_framework_sdk/2.0/zaf_sdk.min.js'
            strategy='beforeInteractive'
          />
          <AppNav />
          {/* <PanelistDetails /> */}
        </div>
        <Component {...pageProps} />
      </main>
    </ThemeProvider>
  )
}

export default NCPApp
